services:
  vue-app:
    build: ../app-abril-24 # Ajusta la ruta según la ubicación del frontend
    container_name: vue-app
    ports:
      - '8080:80'
    depends_on:
      - nest-app

  nest-app:
    build: ../api-abril-24-nest # Ajusta esta ruta según la ubicación del backend
    container_name: nest-app
    ports:
      - '3000:3000'