export const columns = [
  { uid: 'codProducto', name: 'Cod. producto' },
  { uid: 'producto', name: 'Producto' },
  { uid: 'modelo', name: 'Modelo' },
  { uid: 'fabricante', name: 'Fabricante' },
  { uid: 'description', name: 'Descripción' },
  { uid: 'actions', name: 'Acciones' },
];

export const productsData = [
  {
    id: '1',
    CodProducto: '001',
    producto: 'Producto A',
    modelo: 'Modelo A1',
    fabricante: 'Fabricante A',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '1',
    CodProducto: '001',
    producto: 'Producto A',
    modelo: 'Modelo A1',
    fabricante: 'Fabricante A',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '1',
    CodProducto: '001',
    producto: 'Producto A',
    modelo: 'Modelo A1',
    fabricante: 'Fabricante A',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '1',
    CodProducto: '001',
    producto: 'Producto A',
    modelo: 'Modelo A1',
    fabricante: 'Fabricante A',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '1',
    CodProducto: '001',
    producto: 'Producto A',
    modelo: 'Modelo A1',
    fabricante: 'Fabricante A',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '1',
    CodProducto: '001',
    producto: 'Producto A',
    modelo: 'Modelo A1',
    fabricante: 'Fabricante A',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '1',
    CodProducto: '001',
    producto: 'Producto A',
    modelo: 'Modelo A1',
    fabricante: 'Fabricante A',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
  {
    id: '2',
    CodProducto: '002',
    producto: 'Producto B',
    modelo: 'Modelo B1',
    fabricante: 'Fabricante B',
    description: 'Producto A, Modelo, Capacidad',
  },
];
