export interface Imagen {
  CodProducto: string;
  SKU: string | null;
  NImagen: string;
  TipoImagen: string;
  Fecha_Alta: string | null;
  User_Alta: string | null;
  Fecha_Update: string | null;
  User_Update: string | null;
  FileLD: string;
  Observacion: string;
  CodColor: string;
  URL: string;
  Published: string;
  Orden: string;
}

export interface Producto {
  TipoProducto: string;
  CodProducto: string;
  CodNombre: string;
  Producto: string;
  Medida: string;
  Descripcion: string;
  Modelo: string | null;
  CodMarca: string;
  CodRubro: string | null;
  CodCategoria: string;
  Cuenta: string;
  CodBarra: string | null;
  Fabricante: string;
  CodProdProv: string | null;
  CodProveedor: string;
  DatosTecnicos: string | null;
  Fotografia: string | null;
  CodService: string | null;
  TiempoGarantia: string;
  MargenMin: string;
  MargenMax: string;
  Unidad: string;
  Volumen: string;
  ValStock: string;
  Estado: string;
  CodSucLogs: string | null;
  CodLogs: string | null;
  CodFamilia: string;
  VerSerie: string | null;
  Foto: string | null;
  CodAsigProv: string;
  CodSeccion: string;
  Puntaje: string;
  canjePunto: string;
  TipoProveeduria: string;
  ValidarSerie: string;
  PermiteGarExt: string;
  Mailing: string;
  PlanExclusivo: string;
  ActivoPrecio: string;
  PlanesAdmitidos: string;
  activaregalo: string;
  marca: string | null;
  Stock: string | null;
  Link: string | null;
  ImagenFile: string | null;
  volumen_fisico: string | null;
  peso: string | null;
  bultos: string | null;
  vigenciaDesde: string | null;
  vigenciaHasta: string | null;
  idPaisOrigen: string;
  Discontinuo: string | null;
  Fecha_Alta: string | null;
  codSubCategoria: string | null;
  CodSubCategoria_Nivel1: string | null;
  CodSubCategoria_Nivel2: string | null;
  BultosAlCliente: string | null;
  Costo1: string | null;
  Flete: string | null;
  Costo2: string | null;
  Iva: string | null;
  Utilidad: string | null;
  Venta1: string | null;
  Venta2: string | null;
  Comision: string | null;
  NTecnico: string | null;
  Descuento: string | null;
  Activo: string | null;
  Dolar: string | null;
  DolarCosto: string | null;
  ControlaSerie: string | null;
  Manual: string | null;
  Minimo: string | null;
  fechaInicio: string | null;
  fechaFinal: string | null;
  unidDispon: string | null;
  vigCombo: string | null;
  CodPromocion: string | null;
  UBICACION: string | null;
  ActivaPrecio: string | null;
  Promocion_Activa: string | null;
  Promociones_Detalle: string | null;
  CodProducto_rel: string | null;
  User_Edit: string | null;
  id_material: string | null;
  Id_Temporada: string | null;
  id_ocasion: string | null;
  id_linea: string | null;
  Id_TipoBase: string | null;
  StoreId: string | null;
  Publicado: string | null;
  Id_Curva: string | null;
  Fecha_Edit: string | null;
  Fantasia: string | null;
  imagenes: Imagen[]; // Agrega esta línea para incluir la relación de imágenes
}
